live_config_reload = true

import  = [ "~/.config/alacritty/themes/carbonfox.toml" ]

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

[font]
size = 12.5

[font.bold]
family = "MesloLGLDZ Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGLDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGLDZ Nerd Font Mono"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.dimensions]
columns = 208
lines = 46

[window.padding]
x = 0
y = 0
